import { useState } from 'react';
import { ArrowUpRight, ChevronRight } from 'lucide-react';
import { Link } from 'wouter';
import { committees, pillars, stories, type Committee, type Pillar } from '@/data/site';
import SectionLabel from '@/components/shared/SectionLabel';
import ButtonLink from '@/components/shared/ButtonLink';

export default function HomePage() {
  const [activePillar, setActivePillar] = useState<Pillar>(pillars[0]);
  return <div>
    <section className="hero-photo relative min-h-[680px] overflow-hidden pt-[76px] text-[#f4f0e6] lg:min-h-[750px]">
      <div className="dark-grid absolute inset-0 opacity-30" />
      <div className="relative mx-auto grid max-w-[1440px] items-end gap-16 px-5 pb-16 pt-24 sm:px-8 lg:grid-cols-[1.1fr_.9fr] lg:px-12 lg:pb-24 lg:pt-32">
        <div className="reveal max-w-3xl"><SectionLabel light>AN INSTITUTIONAL PLATFORM FOR NORTHERN NIGERIA</SectionLabel><h1 className="display mt-7 text-[clamp(3.2rem,7.8vw,7.4rem)] leading-[.98]">Building a better Northern Nigeria <em className="font-normal text-[#c89b3c]">through</em> knowledge, innovation &amp; action.</h1><p className="mt-8 max-w-lg text-base leading-7 text-[#d2d8d2]">STAND &amp; STEP brings the region’s problem-solvers into one serious, practical network — to ask better questions, build what works and move evidence into the world.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/get-involved" className="inline-flex items-center gap-2 bg-[#c89b3c] px-5 py-3 text-[11px] font-bold tracking-[.1em] text-[#16352b] transition-colors hover:bg-[#f4f0e6]" data-testid="link-hero-join">JOIN THE NETWORK <ArrowUpRight size={14} /></Link><ButtonLink href="/about" dark>WHY STAND &amp; STEP</ButtonLink></div></div>
        <div className="reveal reveal-delay-2 hidden justify-self-end self-end lg:flex lg:max-w-xs lg:flex-col"><div className="mb-5 border-l border-[#c89b3c] pl-4 text-sm leading-6 text-[#d2d8d2]">Science. Technology. Engineering. Perspectives. Action.</div><div className="mono text-[9px] tracking-[.15em] text-[#a9b5ad]">2026 · ESTABLISHMENT &amp; STRATEGIC FRAMEWORK</div></div>
      </div>
      <div className="absolute bottom-0 left-0 right-0 border-t border-white/20"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-4 text-[10px] text-[#b6c0b8] sm:px-8 lg:px-12"><span className="mono">01 / 04 — THE WORK AHEAD</span><span className="hidden items-center gap-2 sm:flex">SCROLL TO EXPLORE <span className="h-8 w-px bg-[#c89b3c]" /></span></div></div>
    </section>
    <section className="site-grid bg-[#f4f0e6] py-20 sm:py-28"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-12"><div className="grid gap-10 lg:grid-cols-[.85fr_1.4fr]"><div><SectionLabel>OUR PURPOSE</SectionLabel><h2 className="display mt-5 max-w-sm text-4xl leading-tight text-[#16352b] sm:text-5xl">Expertise is abundant. <span className="text-[#227a5b]">Connection</span> is the work.</h2></div><div className="max-w-2xl lg:pt-8"><p className="text-xl leading-8 text-[#1b211f] sm:text-2xl">We are building the connective tissue between people who know, people who make and people who decide.</p><p className="mt-6 max-w-xl text-sm leading-7 text-[#66706b]">From a researcher’s finding to a reliable service. From an engineer’s prototype to a working system. From a policy idea to a public outcome. STAND &amp; STEP exists for that journey.</p><ButtonLink href="/about">READ OUR APPROACH</ButtonLink></div></div><div className="mt-20 grid border-y border-[#16352b]/15 sm:grid-cols-3"><Stat value="20" label="Strategic committees" /><Stat value="04" label="Connected practice pillars" /><Stat value="01" label="Shared regional agenda" /></div></div></section>
    <section className="bg-[#16352b] py-20 text-[#f4f0e6] sm:py-28"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-12"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><SectionLabel light>THE PLATFORM</SectionLabel><h2 className="display mt-5 max-w-2xl text-4xl leading-tight sm:text-6xl">Four ways to move a region forward.</h2></div><p className="max-w-xs text-sm leading-6 text-[#b6c0b8]">The pillars share one institutional system — with distinct expertise, a common standard and room for the right questions.</p></div><div className="mt-14 grid border-t border-white/20 lg:grid-cols-[.8fr_1.2fr]"><div className="grid grid-cols-2 border-b border-white/20 lg:block lg:border-b-0 lg:border-r">{pillars.map((pillar) => <button key={pillar.id} onClick={() => setActivePillar(pillar)} className={`flex w-full items-center justify-between border-b border-r border-white/10 px-3 py-5 text-left transition-colors last:border-b-0 sm:px-5 lg:border-r-0 ${activePillar.id === pillar.id ? 'bg-[#227a5b] text-white' : 'text-[#b6c0b8] hover:bg-white/5 hover:text-white'}`} data-testid={`button-pillar-${pillar.id}`}><span><span className="mono block text-[9px] text-[#c89b3c]">{pillar.index}</span><span className="mt-2 block text-sm font-semibold sm:text-base">{pillar.title}</span></span><ChevronRight size={16} /></button>)}</div><div className="relative min-h-[300px] p-7 sm:p-12"><div className="absolute right-8 top-7 text-[8rem] font-bold leading-none text-white/[.035] sm:text-[13rem]">{activePillar.index}</div><div className="relative max-w-lg"><span className="mono text-[10px]" style={{ color: activePillar.accent }}>PILLAR {activePillar.index}</span><h3 className="display mt-5 text-4xl sm:text-5xl">{activePillar.title}</h3><p className="mt-6 text-lg leading-7 text-[#d2d8d2]">{activePillar.description}</p><p className="mt-4 text-sm leading-6 text-[#aab7af]">{activePillar.detail}</p><Link href="/priorities" className="mt-8 inline-flex items-center gap-2 text-[11px] font-bold tracking-[.1em] text-[#c89b3c] hover:text-white" data-testid="link-pillar-explore">EXPLORE THE PRIORITIES <ArrowUpRight size={14} /></Link></div></div></div></div></section>
    <section className="site-grid bg-[#e8e6df] py-20 sm:py-28"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-12"><div className="grid gap-10 lg:grid-cols-[1fr_1fr]"><div><SectionLabel>THE COMMITMENT</SectionLabel><h2 className="display mt-5 max-w-xl text-4xl leading-tight text-[#16352b] sm:text-6xl">20 Strategic Committees. <span className="text-[#227a5b]">One shared agenda.</span> A commitment to impact.</h2></div><div className="flex flex-col justify-end"><p className="max-w-md text-base leading-7 text-[#66706b]">The network is organised around the issues that define the region’s next chapter — not around sectors in isolation.</p><ButtonLink href="/committees">MEET THE COMMITTEES</ButtonLink></div></div><div className="mt-14 grid gap-px bg-[#16352b]/15 md:grid-cols-3">{committees.slice(0, 3).map((committee, i) => <CommitteeCard key={committee.title} committee={committee} index={i} />)}</div></div></section>
    <section className="bg-[#f4f0e6] py-20 sm:py-28"><div className="mx-auto max-w-[1440px] px-5 sm:px-8 lg:px-12"><div className="flex items-end justify-between border-b border-[#16352b]/15 pb-5"><div><SectionLabel>FROM THE PLATFORM</SectionLabel><h2 className="display mt-4 text-4xl text-[#16352b] sm:text-5xl">Ideas with somewhere to go.</h2></div><ButtonLink href="/knowledge-hub">VIEW KNOWLEDGE HUB</ButtonLink></div><div className="grid gap-0 divide-y divide-[#16352b]/15 lg:grid-cols-[1.2fr_1fr_1fr] lg:divide-x lg:divide-y-0">{stories.map((story, i) => <StoryCard story={story} featured={i === 0} key={story.title} />)}</div></div></section>
    <section className="bg-[#227a5b] py-20 text-[#f4f0e6] sm:py-28"><div className="mx-auto grid max-w-[1440px] gap-10 px-5 sm:px-8 lg:grid-cols-[1.2fr_.8fr] lg:items-end lg:px-12"><div><SectionLabel light>AN OPEN INVITATION</SectionLabel><h2 className="display mt-5 max-w-3xl text-5xl leading-[1.02] sm:text-7xl">Be part of the solution.</h2><p className="mt-6 max-w-lg text-base leading-7 text-[#d7e1db]">We cannot transform Northern Nigeria alone. Bring your questions, your practice, your institution — and help make the work useful.</p></div><div className="lg:justify-self-end"><ButtonLink href="/get-involved" dark>FIND YOUR PLACE IN THE NETWORK</ButtonLink></div></div></section>
  </div>;
}

function Stat({ value, label }: { value: string; label: string }) { return <div className="flex items-baseline gap-4 border-b border-[#16352b]/15 px-2 py-6 last:border-0 sm:border-b-0 sm:border-r sm:px-7 sm:first:pl-0 sm:last:border-0"><span className="display text-5xl text-[#227a5b] sm:text-6xl">{value}</span><span className="mono text-[9px] text-[#66706b]">{label}</span></div>; }
function CommitteeCard({ committee, index }: { committee: Committee; index: number }) { return <Link href="/committees" className="group min-h-[220px] bg-[#f4f0e6] p-7 transition-colors hover:bg-[#16352b] hover:text-[#f4f0e6] sm:p-9" data-testid={`card-committee-${index}`}><div className="flex items-start justify-between"><span className="mono text-[9px] text-[#66706b] group-hover:text-[#c89b3c]">0{index + 1} / COMMITTEE</span><ArrowUpRight size={17} className="text-[#227a5b] transition-transform group-hover:translate-x-1 group-hover:-translate-y-1 group-hover:text-[#c89b3c]" /></div><h3 className="display mt-16 text-2xl">{committee.title}</h3><p className="mt-2 text-sm text-[#66706b] group-hover:text-[#b6c0b8]">{committee.focus}</p></Link>; }
function StoryCard({ story, featured }: { story: (typeof stories)[number]; featured?: boolean }) { return <Link href="/knowledge-hub" className={`group block p-7 transition-colors hover:bg-[#e8e6df] sm:p-9 ${featured ? 'lg:row-span-2' : ''}`} data-testid={`card-story-${story.type.toLowerCase().replaceAll(' ', '-')}`}><div className="flex items-center justify-between"><span className="mono text-[9px] text-[#227a5b]">{story.type}</span><span className="mono text-[9px] text-[#66706b]">{story.date}</span></div><h3 className={`display mt-12 leading-tight text-[#16352b] ${featured ? 'text-3xl sm:text-4xl' : 'text-2xl'}`}>{story.title}</h3><p className="mt-5 text-sm leading-6 text-[#66706b]">{story.excerpt}</p><span className="mt-8 inline-flex items-center gap-2 text-[10px] font-bold tracking-[.1em] text-[#16352b] group-hover:text-[#227a5b]">READ MORE <ArrowUpRight size={14} /></span></Link>; }

